# Generated by Django 5.2.5 on 2025-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="company_name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="property_name",
            field=models.CharField(
                blank=True,
                help_text="Name of your property or business",
                max_length=100,
                verbose_name="Property/Business Name",
            ),
        ),
    ]
